---
name: Semgrep Differential Scan
on:
  # push:
  #   branches: []
  pull_request:
    branches: ['master']

jobs:
  semgrep-diff:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: clone application source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: differential scan
        run: |
          semgrep scan \
            --error \
            --verbose \
            --time \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \
            --config="p/default"
